# Generated by Django 5.1.5 on 2025-03-13 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dioses', '0006_alter_ability_ability_type'),
        ('objetos', '0003_alter_item_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dioses.god')),
                ('passive_items', models.ManyToManyField(related_name='passive_builds', to='objetos.item')),
                ('relics', models.ManyToManyField(related_name='relic_builds', to='objetos.item')),
                ('starter_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_builds', to='objetos.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
