# Generated by Django 5.1.5 on 2025-04-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_build_is_random'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Muy mala'), (2, '2 - Mala'), (3, '3 - Regular'), (4, '4 - Buena'), (5, '5 - Excelente')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='builds.build')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('build', 'user')},
            },
        ),
    ]
