from dioses.models import God

def populate_gods():
    # Crear dioses
    gods_data = [
        {"name": "Ra", "pantheon": "Egyptian", "role": "Mage", "difficulty": "Medium", "health": "520 (+80)", "mana": "230 (+45)", "speed": "365", "power": "Magical", "damage": "40 (+1.5)", "attack_speed": "1.00", "progresion": "Escala bien en late game", "proteccion_fisica": "20 (+2)", "proteccion_magica": "30 (+0.8)", "hp5": "10 (+0.8)", "mp5": "6 (+0.5)", "lore": "Ra es el dios solar de Egipto, el cual gobierna sobre la luz y el día.", "image": None},
        {"name": "Anubis", "pantheon": "Egyptian", "role": "Mage", "difficulty": "Hard", "health": "450 (+75)", "mana": "200 (+40)", "speed": "370", "power": "Magical", "damage": "35 (+1.4)", "attack_speed": "1.05", "progresion": "Escalabilidad media, fuerte en el control.", "proteccion_fisica": "15 (+2)", "proteccion_magica": "35 (+1)", "hp5": "8 (+0.7)", "mp5": "7 (+0.6)", "lore": "Anubis, el dios de los muertos, guía a las almas a la otra vida.", "image": None},
        {"name": "Ares", "pantheon": "Greek", "role": "Warrior", "difficulty": "Hard", "health": "550 (+90)", "mana": "200 (+35)", "speed": "375", "power": "Physical", "damage": "40 (+1.6)", "attack_speed": "0.90", "progresion": "Fuertes en combate cuerpo a cuerpo", "proteccion_fisica": "30 (+3)", "proteccion_magica": "20 (+1)", "hp5": "6 (+0.6)", "mp5": "4 (+0.3)", "lore": "Ares, dios de la guerra, es conocido por su fuerza brutal en batalla.", "image": None},
        {"name": "Poseidon", "pantheon": "Greek", "role": "Mage", "difficulty": "Medium", "health": "490 (+85)", "mana": "240 (+50)", "speed": "375", "power": "Magical", "damage": "38 (+1.4)", "attack_speed": "1.05", "progresion": "Escalabilidad media", "proteccion_fisica": "25 (+2)", "proteccion_magica": "30 (+0.8)", "hp5": "9 (+0.8)", "mp5": "8 (+0.7)", "lore": "Poseidón, dios del mar, gobierna las aguas con su tridente.", "image": None},
        {"name": "Artemis", "pantheon": "Greek", "role": "Hunter", "difficulty": "Medium", "health": "480 (+75)", "mana": "220 (+45)", "speed": "370", "power": "Physical", "damage": "34 (+1.3)", "attack_speed": "1.2", "progresion": "Fuerte en el daño a distancia", "proteccion_fisica": "20 (+2)", "proteccion_magica": "25 (+0.6)", "hp5": "7 (+0.7)", "mp5": "5 (+0.5)", "lore": "Artemis, diosa de la caza y la naturaleza, es imparable con su arco.", "image": None},
        {"name": "Odin", "pantheon": "Norse", "role": "Warrior", "difficulty": "Hard", "health": "580 (+100)", "mana": "250 (+45)", "speed": "365", "power": "Physical", "damage": "42 (+1.7)", "attack_speed": "1.00", "progresion": "Fuerte en late game y en duelos", "proteccion_fisica": "35 (+3)", "proteccion_magica": "25 (+0.8)", "hp5": "6 (+0.6)", "mp5": "8 (+0.7)", "lore": "Odin, el padre de todos los dioses nórdicos, es un líder sabio y feroz.", "image": None},
        {"name": "Loki", "pantheon": "Norse", "role": "Assassin", "difficulty": "Medium", "health": "460 (+75)", "mana": "200 (+40)", "speed": "380", "power": "Physical", "damage": "37 (+1.5)", "attack_speed": "1.10", "progresion": "Rápido y con alto daño", "proteccion_fisica": "18 (+2)", "proteccion_magica": "28 (+1)", "hp5": "7 (+0.6)", "mp5": "5 (+0.4)", "lore": "Loki, el dios de las travesuras, usa su astucia y engaños para ganar.", "image": None},
        {"name": "Bastet", "pantheon": "Egyptian", "role": "Assassin", "difficulty": "Medium", "health": "470 (+80)", "mana": "220 (+40)", "speed": "375", "power": "Physical", "damage": "35 (+1.3)", "attack_speed": "1.15", "progresion": "Escalabilidad media", "proteccion_fisica": "20 (+2)", "proteccion_magica": "25 (+0.6)", "hp5": "8 (+0.7)", "mp5": "6 (+0.5)", "lore": "Bastet, diosa felina de Egipto, es conocida por su agilidad y destreza.", "image": None},
        {"name": "Raijin", "pantheon": "Japanese", "role": "Mage", "difficulty": "Medium", "health": "500 (+85)", "mana": "230 (+50)", "speed": "370", "power": "Magical", "damage": "40 (+1.5)", "attack_speed": "1.05", "progresion": "Escalabilidad media", "proteccion_fisica": "15 (+2)", "proteccion_magica": "30 (+0.9)", "hp5": "8 (+0.7)", "mp5": "7 (+0.6)", "lore": "Raijin, el dios del trueno japonés, domina los elementos con su tambor.", "image": None},
    ]
    
    # Crear dioses en la base de datos
    for god_data in gods_data:
        God.objects.create(**god_data)
    
    print("Dioses creados con éxito.")
