# Generated by Django 5.1.5 on 2025-02-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dioses', '0006_alter_ability_ability_type'),
        ('objetos', '0003_alter_item_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('description', models.TextField()),
                ('standard_tracks', models.TextField()),
                ('quests', models.JSONField(help_text='Quests organizadas por semanas')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_description', models.TextField(help_text='Detalles del cambio en la habilidad')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dioses.ability')),
            ],
        ),
        migrations.CreateModel(
            name='GodBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('Buff', 'Buff'), ('Nerf', 'Nerf')], max_length=10)),
                ('general_change', models.TextField(blank=True, help_text='Cambios generales aplicados al dios', null=True)),
                ('abilities_affected', models.ManyToManyField(blank=True, through='news.AbilityBalance', to='dioses.ability')),
                ('god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dioses.god')),
            ],
        ),
        migrations.AddField(
            model_name='abilitybalance',
            name='god_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.godbalance'),
        ),
        migrations.CreateModel(
            name='ItemBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_description', models.TextField(help_text='Detalles del buff/nerf')),
                ('change_type', models.CharField(choices=[('Buff', 'Buff'), ('Nerf', 'Nerf')], default='Buff', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.item')),
            ],
        ),
        migrations.CreateModel(
            name='PatchNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='patch_notes/')),
                ('game_modes', models.TextField(blank=True, help_text='Modos de juego actualizados', null=True)),
                ('new_god_skin', models.CharField(blank=True, max_length=255, null=True)),
                ('new_voice_pack', models.CharField(blank=True, max_length=255, null=True)),
                ('new_god_skin_voice_actors', models.TextField(blank=True, null=True)),
                ('god_balance', models.ManyToManyField(related_name='patches', through='news.GodBalance', to='dioses.god')),
                ('item_balance', models.ManyToManyField(related_name='patches', through='news.ItemBalance', to='objetos.item')),
            ],
        ),
        migrations.AddField(
            model_name='itembalance',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.patchnotes'),
        ),
        migrations.AddField(
            model_name='godbalance',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.patchnotes'),
        ),
    ]
