# Generated by Django 5.1.5 on 2025-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamemodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='jungle_camps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='minimap',
            field=models.ImageField(blank=True, null=True, upload_to='minimaps/'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='statistics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='unique_gameplay_mechanics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
