# Generated by Django 5.1.5 on 2025-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamemodes', '0002_gamemode_jungle_camps_gamemode_minimap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
