# Generated by Django 5.1.5 on 2025-02-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamemodes', '0003_alter_gamemode_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JungleCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gamemode',
            name='jungle_camps',
        ),
        migrations.AddField(
            model_name='gamemode',
            name='jungle_camps',
            field=models.ManyToManyField(blank=True, to='gamemodes.junglecamp'),
        ),
    ]
