# Generated by Django 5.1.5 on 2025-03-20 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dioses', '0006_alter_ability_ability_type'),
        ('objetos', '0003_alter_item_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='GodStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dioses.god')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.IntegerField(default=0)),
                ('usage_type', models.CharField(choices=[('starter', 'Starter Item'), ('passive', 'Passive Item'), ('relic', 'Relic')], max_length=10)),
                ('win_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.item')),
            ],
            options={
                'unique_together': {('item', 'usage_type')},
            },
        ),
    ]
