# Generated by Django 5.1.5 on 2025-03-10 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dioses', '0006_alter_ability_ability_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('S', 'S Tier'), ('A', 'A Tier'), ('B', 'B Tier'), ('C', 'C Tier'), ('D', 'D Tier')], max_length=1)),
                ('god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dioses.god')),
                ('tierlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='tierlist.tierlist')),
            ],
            options={
                'unique_together': {('tierlist', 'god')},
            },
        ),
    ]
