# Generated by Django 5.1.5 on 2025-01-23 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('imp', 'IMP'), ('gestor_hotel', 'Gestor de Hoteles'), ('gestor_recepciones', 'Gestor de Recepciones'), ('gestor_restaurantes', 'Gestor de Restaurantes')], default='gestor_hotel', max_length=20)),
                ('telephone', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
