# Generated by Django 5.1.5 on 2025-01-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ability_type', models.CharField(choices=[('Active', 'Habilidad activa'), ('Passive', 'Habilidad pasiva')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('range', models.FloatField()),
                ('radius', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='abilities/')),
            ],
        ),
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pantheon', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Hunter', 'Cazador'), ('Guardian', 'Guardían'), ('Mage', 'Mago'), ('Warrior', 'Guerrero'), ('Assassin', 'Asesino')], max_length=20)),
                ('health', models.FloatField()),
                ('mana', models.FloatField()),
                ('speed', models.FloatField()),
                ('power', models.FloatField()),
                ('attack_speed', models.FloatField()),
                ('progresion', models.CharField(max_length=50)),
                ('proteccion_fisica', models.FloatField()),
                ('proteccion_magica', models.FloatField()),
                ('hp5', models.FloatField()),
                ('mp5', models.FloatField()),
                ('lore', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gods/')),
                ('abilities', models.ManyToManyField(to='dioses.ability')),
            ],
        ),
    ]
