# Generated by Django 5.1.5 on 2025-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='god',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Fácil'), ('Medium', 'Media'), ('Hard', 'Difícil')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='god',
            name='pantheon',
            field=models.CharField(choices=[('Chinese', 'Chino'), ('Egyptian', 'Egipcio'), ('Greek', 'Griego'), ('Hindu', 'Hindú'), ('Mayan', 'Maya'), ('Norse', 'Nórdico'), ('Roman', 'Romano'), ('Japanese', 'Japonés'), ('Celtic', 'Celta'), ('Slavic', 'Eslavo'), ('Voodoo', 'Vudú'), ('Polynesian', 'Polinesio'), ('Arthurian', 'Artúrico'), ('Babylonian', 'Babilonio'), ('Yoruba', 'Yoruba')], max_length=50),
        ),
    ]
