# Generated by Django 5.1.5 on 2025-01-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioses', '0002_god_difficulty_alter_god_pantheon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='god',
            name='pantheon',
            field=models.CharField(choices=[('Chinese', 'Chino'), ('Egyptian', 'Egipcio'), ('Greek', 'Griego'), ('Hindu', 'Hindú'), ('Mayan', 'Maya'), ('Norse', 'Nórdico'), ('Roman', 'Romano'), ('Japanese', 'Japonés'), ('Celtic', 'Celta'), ('Slavic', 'Eslavo'), ('Voodoo', 'Vudú'), ('Polynesian', 'Polinesio'), ('Arthurian', 'Artúrico'), ('Babylonian', 'Babilonio'), ('Yoruba', 'Yoruba'), ('Great Old Ones', 'Grandes Antiguos')], max_length=50),
        ),
    ]
