# Generated by Django 5.1.5 on 2025-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioses', '0003_alter_god_pantheon'),
    ]

    operations = [
        migrations.AddField(
            model_name='god',
            name='damage',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='god',
            name='attack_speed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='god',
            name='health',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='god',
            name='mana',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='god',
            name='power',
            field=models.CharField(choices=[('Physical', 'Físico'), ('Magical', 'Mágico')], max_length=10),
        ),
        migrations.AlterField(
            model_name='god',
            name='speed',
            field=models.CharField(max_length=50),
        ),
    ]
