# Generated by Django 5.1.5 on 2025-01-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioses', '0004_god_damage_alter_god_attack_speed_alter_god_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='god',
            name='hp5',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='god',
            name='mp5',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='god',
            name='proteccion_fisica',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='god',
            name='proteccion_magica',
            field=models.CharField(max_length=50),
        ),
    ]
