# Generated by Django 5.1.5 on 2025-01-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioses', '0005_alter_god_hp5_alter_god_mp5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability_type',
            field=models.CharField(choices=[('Active 1', 'Habilidad Activa 1'), ('Active 2', 'Habilidad Activa 2'), ('Active 3', 'Habilidad Activa 3'), ('Active 4', 'Habilidad Activa 4'), ('Passive', 'Habilidad Pasiva')], max_length=50),
        ),
    ]
