# Generated by Django 5.1.5 on 2025-02-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
