# Generated by Django 5.1.5 on 2025-02-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0002_item_stats_item_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tier',
            field=models.IntegerField(blank=True, choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), ('Glyph', 'Glifo')], null=True),
        ),
    ]
